"""Generate the README's Current numbers table from the artifacts.

Four review rounds flagged stale numbers. Three of those rounds were "fixed" by
hand and the next round found more, including a mangled sentence introduced by
the fix. The checker added in round three guarded three fractions; the table has
seven rows, so the round-four review found four more wrong numbers inside the
guard's blind spot.

Checking a hand-written table converges slowly. Generating it does not drift at
all. Everything between the markers below is produced from reports/clean/*.json,
so a number in the README that disagrees with its artifact is not possible.

    make numbers        rewrite the table from the artifacts
    make numbers-check  fail if the file is out of date (used by make citations)
"""
from __future__ import annotations

import argparse
import json
import os
import sys

BEGIN = "<!-- BEGIN GENERATED NUMBERS -->"
END = "<!-- END GENERATED NUMBERS -->"
R = "reports/clean"


def _j(name: str) -> dict | None:
    try:
        return json.load(open(os.path.join(R, name)))
    except Exception:
        return None


def render() -> str:
    rows: list[tuple[str, str, str]] = []
    notes: list[str] = []

    ip = _j("intent_proof.json")
    if ip:
        rows.append(("contract cases", f"**{ip['passed']} / {ip['total']}**",
                     f"`{R}/intent_proof.json`"))

    co = _j("corpus.json")
    if co:
        by = co.get("by_category") or {}
        failing = [r["id"] for r in co.get("results", []) if not r.get("passed")]
        rows.append(("accounting corpus",
                     f"**{co['passed']} / {co['total']}** across {len(by)} categories",
                     f"`{R}/corpus.json`"))
        if failing:
            notes.append(
                f"**The {len(failing)} corpus failures are deliberate.** "
                + ", ".join(f"`{f.split('-')[0]}-{f.split('-')[1]}`" for f in failing)
                + " use a raw path that bypasses the contract on purpose, to document "
                  "what ERPNext does natively. Each names the `derivation_map.md` "
                  "finding it documents. They stay failing because they are findings, "
                  "not defects to tune away.")

    bo = _j("boundary.json")
    if bo:
        rows.append(("enforcement boundary", f"**{bo['passed']} / {bo['total']}**",
                     f"`{R}/boundary.json`"))

    ce = _j("census.json")
    if ce:
        v = ce.get("by_verdict", {})
        rows.append(("derivation census",
                     f"{ce['probes_run']} probes, {v.get('protected')} protected, "
                     f"{v.get('silently_accepted')} accepted, {v.get('rejected')} rejected; "
                     f"{len(ce.get('silently_accepted_fields', []))} fields",
                     f"`{R}/census.json`"))

    la = _j("latest.json")
    if la:
        res = {r["mode"]: r for r in la.get("results", [])}
        om, ass = res.get("omit", {}), res.get("assert", {})
        rows.append(("differential",
                     f"{om.get('gap_count', '?')} gaps when `rate` is omitted, "
                     f"{ass.get('gap_count', '?')} when asserted "
                     f"({om.get('ui_grand_total', '?')} vs {ass.get('api_grand_total', '?')})",
                     f"`{R}/latest.json`"))

    si = _j("simulation.json")
    if si:
        st = si.get("stats", {})
        lines = st.get("naive_atlist_lines", 0) + st.get("naive_offlist_lines", 0)
        rows.append(("replay at scale",
                     f"{st.get('naive_written', 0):,} invoices written twice, "
                     f"{lines:,} lines, {st.get('intent_overrides_recorded', 0):,} overrides "
                     f"recorded, {st.get('intent_invariant_failures', 0)} invariant failures, "
                     f"{si.get('elapsed_seconds', 0):.0f}s",
                     f"`{R}/simulation.json`"))

    cc = _j("concurrency.json")
    if cc:
        rows.append(("concurrency",
                     f"integrity {'held' if cc.get('integrity_held') else 'BROKEN'}; "
                     f"{cc.get('succeeded')}/{cc.get('attempted')} writes landed, "
                     f"{cc.get('audit_records_created')} audit records, "
                     f"{cc.get('responses_with_audit_error')} audit errors",
                     f"`{R}/concurrency.json`"))

    rows.append(("trial balance",
                 "guaranteed balanced by construction, therefore uninformative",
                 f"`{R}/trial_balance.json`"))

    out = [BEGIN, "", "| what | result | artifact |", "|---|---|---|"]
    out += [f"| {a} | {b} | {c} |" for a, b, c in rows]
    out += ["",
            "This table is generated by `make numbers` from the JSON artifacts. It is not",
            "maintained by hand, because four review rounds in a row found stale numbers in",
            "it and the hand-fixes introduced new ones.", ""]
    out += [n + "\n" for n in notes]
    out.append(END)
    return "\n".join(out)


EXEC = "docs/EXECUTIVE_SUMMARY.md"
EBEGIN = "<!-- BEGIN GENERATED BOUNDARY -->"
EEND = "<!-- END GENERATED BOUNDARY -->"


def render_exec_boundary() -> str | None:
    """The executive page quotes the boundary count in prose.

    That number is hand-typed nowhere else after this: it goes to readers who
    cannot check it, so it is the last place a stale figure should be able to
    survive. Generated like the table.
    """
    bo = _j("boundary.json")
    if not bo:
        return None
    return f"**{bo['passed']} of {bo['total']} checks pass**"


def sync_exec(check: bool) -> int:
    body = render_exec_boundary()
    if body is None or not os.path.exists(EXEC):
        return 0
    src = open(EXEC, encoding="utf-8").read()
    if EBEGIN not in src or EEND not in src:
        return 0
    head, rest = src.split(EBEGIN, 1)
    _, tail = rest.split(EEND, 1)
    new = head + EBEGIN + body + EEND + tail
    if check:
        if new != src:
            print("  EXECUTIVE_SUMMARY boundary count is STALE. Run: make numbers")
            return 1
        print("  ok   executive summary boundary count matches the artifact")
        return 0
    if new != src:
        open(EXEC, "w", encoding="utf-8").write(new)
        print(f"  executive summary boundary count synced: {body}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    src = open("README.md", encoding="utf-8").read()
    if BEGIN not in src or END not in src:
        print("README.md has no generated-numbers markers; add them once.")
        return 2
    head, rest = src.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + render() + tail

    if a.check:
        rc = 0
        if new != src:
            print("README numbers are STALE. Run: make numbers")
            rc = 1
        else:
            print("  ok   README numbers match the artifacts")
        return rc or sync_exec(check=True)
    open("README.md", "w", encoding="utf-8").write(new)
    print("README Current numbers regenerated from reports/clean/")
    return sync_exec(check=False)


if __name__ == "__main__":
    raise SystemExit(main())
